# Generated by Django 5.0.7 on 2024-07-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blog_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='words',
            field=models.TextField(blank=True, null=True),
        ),
    ]
