# Generated by Django 5.0.7 on 2024-08-03 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blog_status'),
        ('blogs', '0006_alter_blog_short_description'),
    ]

    operations = [
    ]
