# Generated by Django 5.0.7 on 2024-08-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_merge_20240803_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.IntegerField(choices=[(1, 'Published'), (0, 'Draft')], default=0),
        ),
    ]
