# Generated by Django 5.0.7 on 2024-08-09 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0003_alter_social_links_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='social_links',
            options={'verbose_name_plural': 'Social_links'},
        ),
    ]
